"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { AssessmentField, assessmentFields, fieldsInRange, groups } from "./assessment-data";

type RecordData = { id: string; title: string; createdAt: string; updatedAt: string; fields: Record<string, string> };
type Tab = "sheet" | "admission" | "discharge" | "face";
const STORAGE_KEY = "assessment-sheet-local-v2";
const todayTitle = () => { const d = new Date(); return `R${d.getFullYear() - 2018}.${d.getMonth() + 1}.${d.getDate()}　未入力様アセスメント（認定更新）`; };
const emptyRecord = (): RecordData => ({ id: crypto.randomUUID(), title: todayTitle(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), fields: {} });
const textValue = (value?: string) => value ?? "";
const needsReview = (value?: string) => !value?.trim() || value.trim() === "記載なし" || value.trim() === "詳細不明";

export default function Home() {
  const [records, setRecords] = useState<RecordData[]>([]);
  const [activeId, setActiveId] = useState("");
  const [activeTab, setActiveTab] = useState<Tab>("sheet");
  const [pasteOpen, setPasteOpen] = useState(false);
  const [pasteText, setPasteText] = useState("");
  const [message, setMessage] = useState("");
  const importRef = useRef<HTMLInputElement>(null);
  useEffect(() => { const saved = localStorage.getItem(STORAGE_KEY); try { const loaded = saved ? JSON.parse(saved) as RecordData[] : []; if (loaded.length) { setRecords(loaded); setActiveId(loaded[0].id); return; } } catch {} const first = emptyRecord(); setRecords([first]); setActiveId(first.id); }, []);
  useEffect(() => { if (records.length) localStorage.setItem(STORAGE_KEY, JSON.stringify(records)); }, [records]);
  const current = records.find((record) => record.id === activeId) ?? records[0];
  const reviewCount = useMemo(() => current ? assessmentFields.filter((field) => needsReview(current.fields[String(field.id)])).length : 159, [current]);
  const updateCurrent = (mutator: (record: RecordData) => RecordData) => { if (current) setRecords((previous) => previous.map((record) => record.id === current.id ? mutator(record) : record)); };
  const updateField = (id: number | string, value: string) => updateCurrent((record) => { const fields = { ...record.fields, [String(id)]: value }; const name = fields["1"]?.trim(); const autoTitle = record.title.includes("未入力様アセスメント") || record.title.endsWith("様アセスメント（認定更新）"); const title = name && autoTitle ? record.title.replace(/(?:未入力|[^　]+)様アセスメント（認定更新）$/, `${name}様アセスメント（認定更新）`) : record.title; return { ...record, title, fields, updatedAt: new Date().toISOString() }; });
  function createRecord(copy = false) { const base = copy && current ? { ...current, id: crypto.randomUUID(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), fields: { ...current.fields } } : emptyRecord(); const record = copy ? { ...base, title: base.title.replace(/（認定更新）$/, "（認定更新・コピー）") } : base; setRecords((previous) => [record, ...previous]); setActiveId(record.id); setActiveTab("sheet"); setMessage(copy ? "複製を作成しました。内容を更新して保存してください。" : "新しいアセスメントを作成しました。"); }
  function applyPaste() { if (!current) return; const lines = pasteText.replace(/\r/g, "").split("\n").map((line) => line.trim()).filter(Boolean); const numbered = lines.map((line) => { const hit = line.match(/^(?:[-*]\s*)?(\d{1,3})[.．:：\s]+(.+)$/); return hit ? { id: Number(hit[1]), value: hit[2].replace(/^[-*]\s*/, "").trim() } : null; }).filter((item): item is { id: number; value: string } => Boolean(item && item.id >= 1 && item.id <= 159)); const values: Record<string, string> = {}; if (numbered.length >= 20) numbered.forEach((item) => { values[String(item.id)] = item.value; }); else lines.slice(0, 159).forEach((value, index) => { values[String(index + 1)] = value.replace(/^[-*]\s*/, ""); }); const count = Object.keys(values).length; if (!count) { setMessage("貼り付け内容を読み取れませんでした。Google AI Studioの159行の出力をそのまま貼り付けてください。"); return; } updateCurrent((record) => { const fields = { ...record.fields, ...values }; const name = fields["1"]?.trim(); const title = name && record.title.includes("未入力様アセスメント") ? record.title.replace("未入力様アセスメント", `${name}様アセスメント`) : record.title; return { ...record, title, fields, updatedAt: new Date().toISOString() }; }); setPasteOpen(false); setPasteText(""); setMessage(`${count}項目を転記しました。黄色の項目を確認してください。`); }
  function downloadCurrent() { if (!current) return; const blob = new Blob([JSON.stringify(current, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${current.title.replace(/[\\/:*?\"<>|]/g, "_")}.json`; link.click(); URL.revokeObjectURL(url); setMessage("このアセスメントをファイルとして保存しました。アプリ内の履歴にも保存されています。"); }
  function importFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const imported = JSON.parse(String(reader.result)) as RecordData; if (!imported.fields || !imported.title) throw new Error("invalid"); const record = { ...imported, id: crypto.randomUUID(), updatedAt: new Date().toISOString() }; setRecords((previous) => [record, ...previous]); setActiveId(record.id); setMessage("保存済みファイルを読み込みました。"); } catch { setMessage("アセスメントシートから保存したJSONファイルを選んでください。"); } }; reader.readAsText(file); event.target.value = ""; }
  if (!current) return <main className="loading">アセスメントシートを準備しています…</main>;
  return <main className="app-shell"><aside className="sidebar no-print"><div className="app-brand"><div className="brand-icon">✓</div><div><strong>アセスメントシート</strong><span>端末内保存</span></div></div><button className="primary full" onClick={() => createRecord(false)}>＋ 新規アセスメント</button><div className="records-heading"><span>利用者・履歴</span><small>{records.length}件</small></div><div className="record-list">{records.map((record) => <button key={record.id} className={`record-item ${record.id === current.id ? "selected" : ""}`} onClick={() => setActiveId(record.id)}><strong>{record.fields["1"] || "氏名未入力"}</strong><span>{record.title}</span></button>)}</div><div className="storage-note">このPCのブラウザ内だけに保存されます。別のPCには共有されません。</div></aside><section className="work-area"><header className="toolbar no-print"><div className="title-edit"><input aria-label="アセスメントの題名" value={current.title} onChange={(event) => updateCurrent((record) => ({ ...record, title: event.target.value, updatedAt: new Date().toISOString() }))} /><span>最終保存: {new Date(current.updatedAt).toLocaleString("ja-JP")}</span></div><div className="toolbar-actions"><button onClick={() => setPasteOpen(true)}>AI結果を貼り付け</button><button onClick={() => createRecord(true)}>複製</button><button onClick={downloadCurrent}>保存</button><button onClick={() => importRef.current?.click()}>ファイル読込</button><button onClick={() => window.print()}>PDF保存・印刷</button></div><input ref={importRef} type="file" accept="application/json" hidden onChange={importFile} /></header><nav className="tabs no-print"><TabButton active={activeTab === "sheet"} onClick={() => setActiveTab("sheet")} label="エクセルシート" /><TabButton active={activeTab === "admission"} onClick={() => setActiveTab("admission")} label="入院時連携" /><TabButton active={activeTab === "discharge"} onClick={() => setActiveTab("discharge")} label="退院時連携" /><TabButton active={activeTab === "face"} onClick={() => setActiveTab("face")} label="フェイスシート" /><div className="review-pill">要確認 <b>{reviewCount}</b></div></nav>{message && <div className="message no-print" role="status">{message}<button onClick={() => setMessage("")}>×</button></div>}{pasteOpen && <PasteDialog text={pasteText} onChange={setPasteText} onCancel={() => setPasteOpen(false)} onApply={applyPaste} />}<div className="document-wrap">{activeTab === "sheet" && <AssessmentSheets record={current} onChange={updateField} />}{activeTab === "admission" && <AdmissionSheet record={current} onChange={updateField} />}{activeTab === "discharge" && <DischargeSheet record={current} onChange={updateField} />}{activeTab === "face" && <FaceSheet record={current} onChange={updateField} />}</div></section></main>;
}

function TabButton({ active, onClick, label }: { active: boolean; onClick: () => void; label: string }) { return <button className={active ? "active" : ""} onClick={onClick}>{label}</button>; }
function PasteDialog({ text, onChange, onCancel, onApply }: { text: string; onChange: (value: string) => void; onCancel: () => void; onApply: () => void }) { return <div className="modal-backdrop no-print"><section className="paste-dialog" role="dialog" aria-modal="true" aria-labelledby="paste-title"><h2 id="paste-title">Google AI Studioの結果を貼り付け</h2><p>159行の値のみの出力をそのまま貼り付けてください。Markdownの番号付き行にも対応します。</p><textarea autoFocus value={text} onChange={(event) => onChange(event.target.value)} placeholder="ここにAIの出力を貼り付けます" /><div><button onClick={onCancel}>キャンセル</button><button className="primary" onClick={onApply}>自動転記する</button></div></section></div>; }
function AssessmentSheets({ record, onChange }: { record: RecordData; onChange: (id: number | string, value: string) => void }) { return <><section className="paper form-page"><SheetHeader number="No.1" title="基本情報に関する項目" /><div className="form-meta"><ManualField label="今回のアセスメントの理由" id="reason" record={record} onChange={onChange} /><ManualField label="作成年月日" id="created-date" record={record} onChange={onChange} /></div><GroupList groups={groups.basic} record={record} onChange={onChange} /><section className="form-section"><h3>現在利用している支援や社会資源の状況</h3><ManualField label="現在利用中のサービス・事業所名" id="services" record={record} onChange={onChange} multiline /></section><section className="form-section diagram-section"><div><h3>家族構成図</h3><p>かんたんジェノグラムで作成した図のURLを記録します。図を自動貼り付けする連携は次の段階で追加します。</p><ManualField label="かんたんジェノグラムURL" id="genogram-url" record={record} onChange={onChange} /></div><div><h3>住宅見取り図</h3><p>シンプル見取り図で作成した図のURLを記録します。図を自動貼り付けする連携は次の段階で追加します。</p><ManualField label="シンプル見取り図URL" id="floorplan-url" record={record} onChange={onChange} /></div></section></section><section className="paper form-page"><SheetHeader number="No.2" title="課題分析（アセスメント）に関する項目" /><GroupList groups={groups.health} record={record} onChange={onChange} /></section><section className="paper form-page"><SheetHeader number="No.3" title="課題分析（アセスメント）に関する項目" /><GroupList groups={groups.living} record={record} onChange={onChange} /></section></>; }
function SheetHeader({ number, title }: { number: string; title: string }) { return <header className="sheet-header"><div><strong>株式会社K.T.M　リーフケアプランニング　アセスメントシート</strong><span>{title}</span></div><b>{number}</b></header>; }
function GroupList({ groups: groupList, record, onChange }: { groups: { title: string; range: readonly [number, number] }[]; record: RecordData; onChange: (id: number, value: string) => void }) { return <>{groupList.map((group) => <section className="form-section" key={group.title}><h3>【{group.title}】</h3><FieldGrid fields={fieldsInRange(...group.range)} record={record} onChange={onChange} /></section>)}</>; }
function FieldGrid({ fields, record, onChange }: { fields: AssessmentField[]; record: RecordData; onChange: (id: number, value: string) => void }) { return <div className="field-grid">{fields.map((field) => <Field key={field.id} field={field} value={textValue(record.fields[String(field.id)])} onChange={onChange} />)}</div>; }
function Field({ field, value, onChange }: { field: AssessmentField; value: string; onChange: (id: number, value: string) => void }) { const review = needsReview(value); return <label className={`field ${field.multiline ? "wide multiline" : ""}`}><span><small>{field.id}</small>{field.label}</span>{field.multiline ? <textarea className={review ? "review" : ""} value={value} onChange={(event) => onChange(field.id, event.target.value)} /> : <input className={review ? "review" : ""} value={value} onChange={(event) => onChange(field.id, event.target.value)} />}</label>; }
function ManualField({ label, id, record, onChange, multiline = false }: { label: string; id: string; record: RecordData; onChange: (id: string, value: string) => void; multiline?: boolean }) { const value = textValue(record.fields[id]); return <label className={`manual-field ${multiline ? "manual-multiline" : ""}`}><span>{label}</span>{multiline ? <textarea className={needsReview(value) ? "review" : ""} value={value} onChange={(event) => onChange(id, event.target.value)} /> : <input className={needsReview(value) ? "review" : ""} value={value} onChange={(event) => onChange(id, event.target.value)} />}</label>; }
function AdmissionSheet({ record, onChange }: { record: RecordData; onChange: (id: number | string, value: string) => void }) { return <section className="paper connection-sheet"><h1>フェースシート・情報提供書</h1><p className="sheet-subtitle">入院時連携用　利用者（患者）／家族の同意に基づく情報提供</p><section className="connection-block"><h2>1. 利用者（患者）基本情報について</h2><FieldGrid fields={fieldsInRange(1, 28)} record={record} onChange={onChange} /><ManualField label="担当ケアマネジャー名" id="care-manager" record={record} onChange={onChange} /></section><section className="connection-block"><h2>2. 身体・生活機能の状況／療養上の課題について</h2><FieldGrid fields={[...fieldsInRange(49, 99), ...fieldsInRange(109, 140)]} record={record} onChange={onChange} /><ManualField label="生活歴及び直近2週間以内の心身状況" id="admission-note" record={record} onChange={onChange} multiline /></section></section>; }
function DischargeSheet({ record, onChange }: { record: RecordData; onChange: (id: number | string, value: string) => void }) { return <section className="paper connection-sheet"><h1>退院・退所情報記録書</h1><section className="connection-block"><h2>1. 基本情報・現在の状態 等</h2><FieldGrid fields={[...fieldsInRange(1, 7), ...fieldsInRange(21, 21), ...fieldsInRange(29, 55), ...fieldsInRange(56, 99), ...fieldsInRange(116, 140)]} record={record} onChange={onChange} /><ManualField label="入退院日・入院経緯" id="discharge-stay" record={record} onChange={onChange} multiline /><ManualField label="退院後の生活に関する本人・家族の意向" id="discharge-wishes" record={record} onChange={onChange} multiline /></section><section className="connection-block"><h2>2. 課題認識のための情報</h2><ManualField label="医療処置の内容" id="medical-care" record={record} onChange={onChange} multiline /><ManualField label="看護の視点" id="nursing" record={record} onChange={onChange} multiline /><ManualField label="リハビリの視点" id="rehabilitation" record={record} onChange={onChange} multiline /><ManualField label="備考" id="discharge-notes" record={record} onChange={onChange} multiline /></section></section>; }
function FaceSheet({ record, onChange }: { record: RecordData; onChange: (id: number | string, value: string) => void }) { return <section className="paper connection-sheet face-sheet"><h1>フェイスシート</h1><p className="sheet-subtitle">このページは現在作成準備中です。自動転記可能な基本情報を先に表示しています。</p><section className="connection-block"><h2>基本情報</h2><FieldGrid fields={[...fieldsInRange(1, 15), ...fieldsInRange(20, 28), ...fieldsInRange(49, 54)]} record={record} onChange={onChange} /></section><section className="connection-block"><h2>追加入力</h2><ManualField label="フェイスシート用の特記事項" id="face-note" record={record} onChange={onChange} multiline /></section></section>; }
